name: CI - Main
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Create env file
        run: |
          touch .env
          echo ATLAS_URI=${{ vars.ATLAS_URI }} >> .env
          echo PORT=${{ vars.PORT }} >> .env
          echo MAPS_KEY=${{ secrets.MAPS_KEY }} >> .env

      - name: Install PM2
        run: npm i -g pm2

      - name: Deploy
        run: |
          env $(cat .env | grep -v \"#\" | xargs) pm2 deploy ecosystem.config.cjs production setup
          env $(cat .env | grep -v \"#\" | xargs) pm2 deploy ecosystem.config.cjs production